name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Build
        run: |
          yarn
          npx gulp all
      - uses: actions/upload-artifact@v2
        with:
          name: Hydro.zip
          path: Hydro.zip
